version: "3.9"

services:
  shorturl_db:
    image: postgres
    env_file:
      - .env
    volumes: 
     - ./static/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  shorturl_app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - shorturl_db
    ports:
      - "8080:8080"
    restart: on-failure:4


   